language: cpp

sudo: required
dist: trusty

compiler: clang

addons:
    apt:
      packages:
        - cmake
        - opencv
      sources:
        - kalakris-cmake

script: 
  - mkdir build
  - cd build
  - cmake .. 
