language: cpp

sudo: required
dist: trusty

compiler: clang

addons:
    apt:
      packages:
        - cmake
      sources:
        - kalakris-cmake

script: 
  - mkdir build
  - make
  - cmake .. & make
