language: cpp

sudo: required
dist: trusty

compiler: clang

addons:
    apt:
      packages:
        - cmake
      sources:
        - kalakris-cmake

before_script:
  - curl -sL https://github.com/Itseez/opencv/archive/3.1.0.zip > opencv.zip
  - unzip opencv.zip
  - cd opencv-3.1.0

  - mkdir build install
  - cd build
  - cmake -D CMAKE_BUILD_TYPE=RELEASE -DBUILD_SHARED_LIBS=OFF -D CMAKE_INSTALL_PREFIX=$(pwd)/../install -D WITH_FFMPEG=OFF -D WITH_IPP=OFF ..
#  - cmake -D CMAKE_BUILD_TYPE=RELEASE -D CMAKE_INSTALL_PREFIX=$(pwd)/../install -D WITH_TBB=ON -D BUILD_NEW_PYTHON_SUPPORT=ON -D WITH_V4L=ON -D INSTALL_C_EXAMPLES=ON -D INSTALL_PYTHON_EXAMPLES=ON -D BUILD_EXAMPLES=ON -D WITH_QT=ON -D WITH_OPENGL=ON -D WITH_FFMPEG=OFF ..
  - make -j4
  - make install

- cd ../../

script: 
  - mkdir build
  - cd build
  - cmake .. 
