language: cpp

compiler:
  - gcc

addons:
  apt:
    sources:
      - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
    packages:
      - cd DGM
      - cmake
      - cmake-data

before_script:
  - mkdir build
  - cmake ..

script: make
