language: cpp

os:
  - windows

compiler:
  - gcc

addons:
  apt:
    sources:
      - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
    packages:
      - cmake
      - cmake-data

before_script:
  - cd DGM
  - mkdir build
  - cmake ..

script: make
