#-----------------------------------------------------------------------------
#  Configuration for continuous integration service at appveyor.com
#-----------------------------------------------------------------------------
version: 1.5.0:{build}

branches:
  only:
  - master

# Operating system (build VM template)
os: Visual Studio 2015

# scripts that are called at very beginning, before repo cloning
init:

# clone directory
clone_folder: c:\projects\dgm

# platform: x64

#install:
#  -cmd: choco install OpenCV

build_script:
  - choco install OpenCV '/InstallationPath:C:\OpenCV'
  - cd C:\OpenCV
  - dir
  - cd c:\projects\dgm
  - md build
  - cd build
  - cmake -DOPENCV_DIR="c:\opencv" -G"Visual Studio 14" ..
  - msbuild /m /p:Configuration=Release /p:Platform="Win32" DGM.sln
