#-----------------------------------------------------------------------------
#  Configuration for continuous integration service at appveyor.com
#-----------------------------------------------------------------------------
version: 1.5.0:{build}

branches:
  only:
  - master

# Operating system (build VM template)
os: Visual Studio 2015

# scripts that are called at very beginning, before repo cloning
init:

# clone directory
clone_folder: c:\projects\dgm

# platform: x64

install:
  -ps: choco install opencv

build_script:
  - cd c:\
  - dir
  - cd c:\projects\dgm
  - md build
  - cd build
  - cmake -G"Visual Studio 14" ..
  - msbuild /m /p:Configuration=Release /p:Platform="Win32" DGM.sln
